### ISSUE TITLE
not working on macos safari 11.0.3 and ios11.2.6 safari 

### ISSUE THREAD

**Issue by latel** [aralejs/name-storage#4]

**Comment by hotoo** [comment]
What's the error information?

**Comment by latel** [comment]
@hotoo no error is thrown, just window.name is empty cross domains, you can test it

**Comment by hotoo** [comment]
Oh yes, name-storage died.

**Comment by latel** [comment]
ugly  safari

**Comment by latel** [comment]
I think you had better mention this on the readme @hotoo
